name: pytask-environment

channels:
  - conda-forge
  - nodefaults

dependencies:
  - python >=3.6
  - pip
  - setuptools_scm
  - toml

  # Package dependencies
  - pytask >=0.2

  # Misc
  - pre-commit
  - pytest
  - pytest-cov
