{% set data = load_setup_py_data() %}

package:
  name: pytask-environment
  version: {{ data.get('version') }}

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only captures
  # committed code, so pay attention.
  git_url: ../

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python >=3.6
    - pytask >=0.0.7

test:
  requires:
    - pytest
  source_files:
    - tox.ini
    - tests
  commands:
    - pytask --version
    - pytask --help
    - pytask clean
    - pytask markers

    - pytest tests

about:
  home: https://github.com/pytask-dev/pytask-environment
  license: MIT
  license_file: LICENSE
  summary: Ensure checks on the current Python environment.
  dev_url: https://github.com/pytask-dev/pytask-environment/
